### ISSUE TITLE
Samples for Using Core API

### ISSUE THREAD

**Issue by raskolnikov1041** [valor-software/ng2-handsontable#372]
First of all, thanks for the great work.   I have searched through all the closed issues and codes but couldn't seem to find an example of a use case whereby the HOT APIs are being used.  For example, I would like to get the underlying data of a sorted table using getData(r, c, r2, c2) from my component where the HOT is rendered.

Would you be so kind to point me to a documentation or a sample?

Thanks so much.

**Comment by renehamburger** [comment]
Did you have a look at the demo sources? The include a few examples of accessing the Handsontable API directly, e.g. https://github.com/valor-software/ng2-handsontable/blob/master/demo/src/components/handsontable/advanced-demo.ts.

I'm sure you are aware of the hooks that can be added to the options object directly. Sometimes they can be used instead of calling the API directly.
