### ISSUE TITLE
angular4 with custom validator

### ISSUE THREAD

**Issue by troddick** [valor-software/ng2-handsontable#472]
Thanks for the great library! I've used it quite a bit for my angularJS projects. This is my first angular4 project where I need the handsontable library. I am trying to write a few custom validators for my columns. I have a 2 questions:

- Is there a built-in requiredValidator for cells?

- Could you provide an example of what a custom validator would look like in Typescript (where I have access to the row/col/prop info AND my component properties too? I have tried it two ways. 
  1) inline:
       `this.columns = [ {data: 'name', validator: (value, callback) => { ....}}, ... `
   This allows me access to `this` being my component properties, but I don't have access to the row/column/prop/instance that I am validating.
  2) as a separate function: 
       `private matchingDDValidator(value, callback) { ..... }`
      This allows me access to `this` being the columnSettings (row/column/prop/instance) but not any of my component properties.

Am I missing something? I have searched and searched for an example of doing a validator with the new angular2+ syntax. The examples I have found have all been for renderers. 

Thanks.

**Comment by renehamburger** [comment]
Hi @troddick,

ng2-handsontable doesn't implement any validators and the list of [built-in validators in handsontable](https://docs.handsontable.com/0.33.0/Options.html#validator) does not include a requiredValidator.

If you need to access both the component and the `this` context of the function you need to use `function ()` instead of the fat arrow function, while also saving the component's `this` to another variable in the function's closure, e.g. `const that = this`.

Alternatively, if the handsontable instance is all you need, you can use `@ViewChild(HotTable) hotTableComponent` and `hotTableComponent.getHandsontableInstance()`.
